### ISSUE TITLE
Understanding LinkLabel

### ISSUE THREAD

**Issue by JMichaelTX** [npalardy/LinkLabel#1]
Norm @npalardy, thanks for sharing this class.

As you know I am very new to Xojo, so I am trying to understand how your class works.
So I hope you don't mind if I ask a few questions:

1. How does the display value of the instance (`LinkLabel1.value`) get set?
   * I have looked everywhere, and searched, and cannot find where this is done
   * In the IDE it shows as "Untitled".
2. When is the Computed Property URL called and Set?
   * Are Computed Properties Set method auto-called when an App or Window is opened?
   * I was concerned that the URL validation was being called everytime the user clicked on the label, but maybe not.
3. Why is the last instance, `LinkLabel4.URL`, with a URL of "stuff" treated like a hyperlink?
   *  Obviously it is not a URL, yet it is displayed as one, with an underline, and when I click on it, it tries to open in my browser.

Thanks again.

**Comment by JMichaelTX** [comment]
Norm, after further analysis, I believe your URI/URL validation is flawed, since an entry of "stuff" passes your test.

From the `URL Set()` method:
```
'results In the following subexpression matches:
'
'$1 = http:
'$2 = http
'$3 = //www.ics.uci.edu
'$4 = www.ics.uci.edu
'$5 = /pub/ietf/uri/
'$6 = <undefined>
'$7 = <undefined>
'$8 = #Related
```
Capture Group #4 is essential to any valid URL, and must contain at least two words separated by a dot, as in `xojo.com`.    So, if it fails the first test, as "stuff" does, then you prefix "https://" and test again.

The results of CG#4 of the second test must match this:
`([^\.]+).([^\.]+)`

"https://stuff" would FAIL that test.

**Comment by npalardy** [comment]
The validation regex comes directly from the RFC's

**Comment by JMichaelTX** [comment]
> The validation regex comes directly from the RFC's

Yes, but "stuff" FAILS the RFC.  The next part is of your design, NOT RFC.  That is the part which is flawed.

**Comment by JMichaelTX** [comment]
From the RFC Spec:

>Such a name consists of a sequence of domain labels separated by ".",
   each domain label starting and ending with an alphanumeric character
   and possibly also containing "-" characters.  The rightmost domain
   label of a fully qualified domain name in DNS may be followed by a
   single "." and should be if it is necessary to distinguish between
   the complete domain name and some local domain.

If CG#4 does NOT conform to this spec for a domain, then it is NOT valid.

**Comment by npalardy** [comment]
> Norm @npalardy, thanks for sharing this class.
> 
> As you know I am very new to Xojo, so I am trying to understand how your class works.
> So I hope you don't mind if I ask a few questions:
> 
> 1. How does the display value of the instance (`LinkLabel1.value`) get set?
>    
In older IDE's where I primarily work this is a property known as Text
I'll fix this so it doesn't show since its not useful

>    * I have looked everywhere, and searched, and cannot find where this is done
>    * In the IDE it shows as "Untitled".
Its a property inherited from the super class

> 2. When is the Computed Property URL called and Set?
When code gets or sets it 
This may or may not be code you manually write as the IDE generates a lot of code for you from the layout

>    * Are Computed Properties Set method auto-called when an App or Window is opened?
See above - they may be

>    * I was concerned that the URL validation was being called everytime the user clicked on the label, but maybe not.
No

> 3. Why is the last instance, `LinkLabel4.URL`, with a URL of "stuff" treated like a hyperlink?
Because the regex from the RFC validates it one    
See https://tools.ietf.org/html/rfc3986#page-50

>    * Obviously it is not a URL, yet it is displayed as one, with an underline, and when I click on it, it tries to open in my browser.

**Comment by JMichaelTX** [comment]
> In older IDE's where I primarily work this is a property known as Text
> I'll fix this so it doesn't show since its not useful

I figured it out.  Here's my fix:

```vbscript
If Me.Value = "Untitled" Then
  Me.Value = value    //CHG JMTX
End If
```

**Comment by npalardy** [comment]
> > In older IDE's where I primarily work this is a property known as Text
> > I'll fix this so it doesn't show since its not useful
> 
> I figured it out. Here's my fix:
> 
> ```vbnet
> If Me.Value = "Untitled" Then
>   Me.Value = value    //CHG JMTX
> End If
> ```

That has no effect IN the IDE but would change things at runtime

**Comment by JMichaelTX** [comment]
> That has no effect IN the IDE but would change things at runtime

Thanks, but I knew that since I made the change.  LOL
The point is to allow the app designer to set the text of the link, and use that, or change the text to the URL if not.

**Comment by npalardy** [comment]
yeah it the property that we're trying to deal with wasnt named the same as a data type there is more we could do

I could hack things to make it work but anyone making any chnage to the class would eventually have problems and would have to do the same hack :)

**Comment by JMichaelTX** [comment]
Norm, I think we need to re-think use of the UTI RTC  It allow to much flexibility.  For example it does NOT require a domain name.

What we are concerned with are [Custom URL Schemes](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app), which I believe fall into two main categories:
1. Those that start with "http" or "ftp", which require a valid domain name,
2. All others, that start with the URL scheme registered with Apple, this includes:
   * "mailto:"
   * Others like "omnifocus://"

I think that is easy enough to implement.  I'll take a look at it.

**Comment by npalardy** [comment]
you can fork this and make your own based on this
I use this the way it is

**Comment by JMichaelTX** [comment]
Here's my proposal.  Requires only one RegEx search, unless you want to try again with the original URL with prefix of "https".

https://regex101.com/r/3MRqVf/1/

I'll do some more testing with this RegEx in the class, and then post in the Xojo forum for review.
